/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Dec 02 21:31:54 GMT 2017
 */

package controllers;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class ApplicationController_ESTest_scaffolding {

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "controllers.ApplicationController"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init(); 
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.specification.version", "1.8"); 
            java.lang.System.setProperty("java.home", "C:\\Program Files\\Java\\jdk1.8.0_144\\jre"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\devon"); 
            java.lang.System.setProperty("java.awt.headless", "true"); 
                                java.lang.System.setProperty("user.dir", "C:\\Users\\devon\\Documents\\Java Projects\\AcesUp"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\devon\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("awt.toolkit", "sun.awt.windows.WToolkit"); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("file.separator", "\\"); 
        java.lang.System.setProperty("java.awt.graphicsenv", "sun.awt.Win32GraphicsEnvironment"); 
    java.lang.System.setProperty("java.awt.printerjob", "sun.awt.windows.WPrinterJob"); 
    java.lang.System.setProperty("java.class.path", "C:\\Users\\devon\\AppData\\Local\\Temp\\EvoSuite_pathingJar1570628914190883328.jar"); 
    java.lang.System.setProperty("java.class.version", "52.0"); 
        java.lang.System.setProperty("java.endorsed.dirs", "C:\\Program Files\\Java\\jdk1.8.0_144\\jre\\lib\\endorsed"); 
    java.lang.System.setProperty("java.ext.dirs", "C:\\Program Files\\Java\\jdk1.8.0_144\\jre\\lib\\ext;C:\\WINDOWS\\Sun\\Java\\lib\\ext"); 
    java.lang.System.setProperty("java.library.path", "lib"); 
    java.lang.System.setProperty("java.runtime.name", "Java(TM) SE Runtime Environment"); 
    java.lang.System.setProperty("java.runtime.version", "1.8.0_144-b01"); 
    java.lang.System.setProperty("java.specification.name", "Java Platform API Specification"); 
    java.lang.System.setProperty("java.specification.vendor", "Oracle Corporation"); 
        java.lang.System.setProperty("java.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor.url", "http://java.oracle.com/"); 
    java.lang.System.setProperty("java.version", "1.8.0_144"); 
    java.lang.System.setProperty("java.vm.info", "mixed mode"); 
    java.lang.System.setProperty("java.vm.name", "Java HotSpot(TM) 64-Bit Server VM"); 
    java.lang.System.setProperty("java.vm.specification.name", "Java Virtual Machine Specification"); 
    java.lang.System.setProperty("java.vm.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.specification.version", "1.8"); 
    java.lang.System.setProperty("java.vm.version", "25.144-b01"); 
    java.lang.System.setProperty("line.separator", "\r\n"); 
    java.lang.System.setProperty("os.arch", "amd64"); 
    java.lang.System.setProperty("os.name", "Windows 10"); 
    java.lang.System.setProperty("os.version", "10.0"); 
    java.lang.System.setProperty("path.separator", ";"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "devon"); 
    java.lang.System.setProperty("user.timezone", "America/Los_Angeles"); 
              }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ApplicationController_ESTest_scaffolding.class.getClassLoader() ,
      "org.joda.time.DateTimeZone",
      "com.google.common.collect.Lists$RandomAccessPartition",
      "com.google.common.collect.Collections2",
      "org.apache.commons.lang.exception.NestableException",
      "org.apache.commons.configuration.AbstractConfiguration",
      "models.Deck",
      "com.google.common.collect.ImmutableCollection$ArrayBasedBuilder",
      "org.joda.time.DateTimeFieldType$StandardDateTimeFieldType",
      "ninja.session.FlashScope",
      "org.joda.time.chrono.BasicChronology$HalfdayField",
      "org.joda.time.chrono.BasicChronology$YearInfo",
      "org.joda.time.field.UnsupportedDurationField",
      "ninja.WrappedContext",
      "org.joda.time.ReadWritableInterval",
      "ninja.Cookie",
      "com.google.common.base.Predicate",
      "org.apache.commons.fileupload.FileItemIterator",
      "org.joda.time.base.BaseLocal",
      "org.joda.time.chrono.ISOChronology",
      "models.SpanishDeck",
      "org.joda.time.field.DividedDateTimeField",
      "com.google.common.base.Joiner",
      "org.joda.time.convert.DateConverter",
      "org.apache.commons.configuration.Configuration",
      "org.joda.time.chrono.ZonedChronology",
      "org.joda.time.format.DateTimeFormatterBuilder$TimeZoneOffset",
      "org.joda.time.field.BaseDateTimeField",
      "org.joda.time.field.ZeroIsMaxDateTimeField",
      "ninja.utils.DateUtil",
      "org.joda.time.format.FormatUtils",
      "com.google.common.collect.Lists$Partition",
      "models.Column",
      "com.google.common.collect.Lists",
      "org.joda.time.convert.LongConverter",
      "com.google.common.collect.UnmodifiableListIterator",
      "org.joda.time.base.AbstractInstant",
      "org.joda.time.tz.DateTimeZoneBuilder",
      "org.joda.time.format.DateTimeParserBucket",
      "org.apache.commons.configuration.PropertiesConfiguration",
      "com.google.common.base.Absent",
      "com.google.common.collect.Maps$BiMapConverter",
      "org.joda.time.ReadWritablePeriod",
      "org.apache.commons.configuration.event.EventSource",
      "com.google.common.base.CharMatcher",
      "com.google.common.base.Joiner$MapJoiner",
      "org.joda.time.LocalDateTime",
      "org.joda.time.tz.FixedDateTimeZone",
      "org.joda.time.convert.IntervalConverter",
      "org.joda.time.field.PreciseDateTimeField",
      "com.google.common.base.CharMatcher$5",
      "com.google.common.base.CharMatcher$4",
      "com.google.common.base.CharMatcher$3",
      "com.google.common.base.CharMatcher$2",
      "org.joda.time.chrono.GJLocaleSymbols",
      "com.google.common.base.CharMatcher$9",
      "com.google.common.base.CharMatcher$8",
      "com.google.common.base.CharMatcher$7",
      "com.google.common.base.CharMatcher$6",
      "org.joda.time.convert.ReadableDurationConverter",
      "com.google.common.base.Preconditions",
      "org.joda.time.field.DecoratedDateTimeField",
      "com.google.common.base.CharMatcher$1",
      "com.google.common.base.CharMatcher$FastMatcher",
      "com.google.common.base.Joiner$1",
      "ninja.uploads.FileItem",
      "org.joda.time.format.DateTimeFormatterBuilder$TimeZoneId",
      "com.google.common.base.Joiner$2",
      "org.joda.time.YearMonthDay",
      "org.joda.time.format.DateTimeFormatterBuilder$CharacterLiteral",
      "com.google.common.collect.AbstractNavigableMap",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.collect.ImmutableEnumMap",
      "org.joda.time.DateTime$Property",
      "org.joda.time.convert.ReadablePeriodConverter",
      "org.joda.time.field.OffsetDateTimeField",
      "org.joda.time.convert.ReadableIntervalConverter",
      "com.google.common.base.CharMatcher$BitSetMatcher",
      "controllers.ApplicationController",
      "org.joda.time.DateTimeField",
      "com.google.common.collect.ImmutableCollection$Builder",
      "com.google.common.collect.BiMap",
      "com.google.common.collect.Lists$AbstractListWrapper",
      "ninja.utils.ResponseStreams",
      "org.joda.time.DateTimeUtils$SystemMillisProvider",
      "org.joda.time.chrono.GJDayOfWeekDateTimeField",
      "org.joda.time.IllegalInstantException",
      "org.joda.time.IllegalFieldValueException",
      "org.joda.time.format.DateTimeFormatterBuilder$Composite",
      "org.joda.time.field.ImpreciseDateTimeField$LinkedDurationField",
      "org.joda.time.ReadablePeriod",
      "org.joda.time.chrono.ZonedChronology$ZonedDateTimeField",
      "org.joda.time.chrono.GregorianChronology",
      "com.google.common.collect.Lists$StringAsImmutableList",
      "com.google.common.collect.Lists$2",
      "org.joda.time.convert.ConverterManager",
      "com.google.common.collect.Maps$FilteredEntryBiMap",
      "ninja.Route",
      "com.google.common.collect.Lists$1",
      "org.joda.time.format.DateTimeFormatterBuilder$PaddedNumber",
      "org.joda.time.chrono.BasicMonthOfYearDateTimeField",
      "org.apache.commons.configuration.FileSystemBased",
      "models.Game",
      "org.joda.time.base.AbstractPartial",
      "org.joda.time.base.BasePartial",
      "org.joda.time.base.BaseDateTime",
      "org.joda.time.DateTimeUtils",
      "com.google.common.collect.Multiset",
      "com.google.common.base.Supplier",
      "org.joda.time.LocalTime",
      "org.joda.time.field.DecoratedDurationField",
      "org.joda.time.tz.DateTimeZoneBuilder$DSTZone",
      "com.google.common.collect.Maps$ImprovedAbstractMap",
      "com.google.common.collect.ImmutableList",
      "org.joda.time.TimeOfDay",
      "com.google.common.collect.Maps$FilteredEntrySortedMap",
      "org.joda.time.field.ImpreciseDateTimeField",
      "org.joda.time.field.PreciseDurationField",
      "org.joda.time.tz.DateTimeZoneBuilder$OfYear",
      "org.joda.time.ReadableDuration",
      "org.joda.time.chrono.BasicGJChronology",
      "org.joda.time.format.DateTimeFormatterBuilder$NumberFormatter",
      "org.joda.time.format.DateTimeFormatter",
      "org.joda.time.DurationField",
      "org.joda.time.format.DateTimeFormatterBuilder$TimeZoneName",
      "org.joda.time.DateTime",
      "org.apache.commons.lang.exception.Nestable",
      "com.google.common.collect.Maps$EntryTransformer",
      "org.joda.time.convert.PeriodConverter",
      "org.joda.time.chrono.ZonedChronology$ZonedDurationField",
      "org.joda.time.convert.CalendarConverter",
      "org.joda.time.DurationFieldType$StandardDurationFieldType",
      "org.joda.time.chrono.BasicDayOfYearDateTimeField",
      "ninja.validation.Validation",
      "org.joda.time.chrono.BuddhistChronology",
      "ninja.Context",
      "com.google.common.collect.ImmutableList$SubList",
      "org.joda.time.format.DateTimeFormatterBuilder$StringLiteral",
      "org.joda.time.tz.DateTimeZoneBuilder$Recurrence",
      "org.joda.time.convert.ReadablePartialConverter",
      "org.joda.time.convert.Converter",
      "org.joda.time.DateTimeUtils$MillisProvider",
      "org.joda.time.chrono.GJYearOfEraDateTimeField",
      "org.joda.time.convert.PartialConverter",
      "com.google.common.collect.RegularImmutableList",
      "com.google.common.base.Optional",
      "org.joda.time.field.RemainderDateTimeField",
      "org.joda.time.JodaTimePermission",
      "org.joda.time.chrono.BasicWeekOfWeekyearDateTimeField",
      "com.google.common.collect.Lists$TransformingRandomAccessList",
      "org.joda.time.DateTimeFieldType",
      "org.joda.time.format.DateTimeFormatterBuilder$Fraction",
      "com.google.inject.ImplementedBy",
      "com.google.common.base.CharMatcher$NegatedFastMatcher",
      "ninja.utils.SwissKnife",
      "org.joda.time.ReadableInterval",
      "org.joda.time.tz.DateTimeZoneBuilder$PrecalculatedZone",
      "com.google.common.collect.SortedMapDifference",
      "org.joda.time.base.AbstractDateTime",
      "org.joda.time.convert.AbstractConverter",
      "com.google.inject.ScopeAnnotation",
      "org.joda.time.chrono.BasicChronology",
      "com.google.common.collect.Maps$AbstractFilteredMap",
      "com.google.common.base.Present",
      "org.joda.time.chrono.BasicYearDateTimeField",
      "org.apache.commons.configuration.ConfigurationException",
      "com.google.inject.Singleton",
      "org.apache.commons.configuration.FileConfiguration",
      "org.joda.time.format.DateTimeFormatterBuilder",
      "com.google.common.collect.ImmutableAsList",
      "org.joda.time.tz.CachedDateTimeZone$Info",
      "com.google.common.collect.RegularImmutableAsList",
      "com.google.common.collect.Maps$FilteredEntryMap",
      "ninja.Result",
      "org.joda.time.PeriodType",
      "org.joda.time.field.MillisDurationField",
      "org.joda.time.format.InternalPrinter",
      "ninja.Renderable",
      "org.joda.time.chrono.GJChronology",
      "org.joda.time.format.DateTimeFormatterBuilder$TextField",
      "org.joda.time.field.UnsupportedDateTimeField",
      "com.google.common.collect.Lists$TransformingSequentialList",
      "org.joda.time.field.ScaledDurationField",
      "org.joda.time.chrono.ISOYearOfEraDateTimeField",
      "com.google.common.collect.ObjectArrays",
      "com.google.common.base.CaseFormat$1",
      "org.apache.commons.configuration.AbstractFileConfiguration",
      "com.google.common.base.CaseFormat$2",
      "com.google.common.base.CaseFormat$3",
      "org.joda.time.field.PreciseDurationDateTimeField",
      "com.google.common.base.CharMatcher$NegatedMatcher",
      "com.google.common.base.CaseFormat$4",
      "com.google.common.base.CaseFormat$5",
      "com.google.common.base.CharMatcher$And",
      "com.google.common.collect.ImmutableList$1",
      "org.joda.time.tz.CachedDateTimeZone",
      "com.google.common.collect.MapDifference",
      "org.joda.time.ReadableDateTime",
      "com.google.common.collect.UnmodifiableIterator",
      "org.joda.time.DateMidnight",
      "com.google.common.collect.Maps$FilteredEntryNavigableMap",
      "com.google.common.base.CharMatcher$12",
      "com.google.common.base.CharMatcher$11",
      "com.google.common.base.CharMatcher$10",
      "com.google.common.base.CharMatcher$15",
      "com.google.common.base.CharMatcher$14",
      "com.google.common.collect.Lists$RandomAccessListWrapper",
      "com.google.common.base.CharMatcher$13",
      "org.joda.time.convert.DurationConverter",
      "org.joda.time.chrono.GJMonthOfYearDateTimeField",
      "org.joda.time.chrono.BasicWeekyearDateTimeField",
      "com.google.common.collect.ImmutableList$ReverseImmutableList",
      "ninja.validation.ValidationImpl",
      "com.google.common.base.CharMatcher$RangesMatcher",
      "com.google.common.collect.SingletonImmutableList",
      "org.joda.time.format.DateTimeFormatterBuilder$MatchingParser",
      "com.google.common.base.Converter",
      "org.joda.time.format.DateTimeFormat",
      "com.google.common.base.Function",
      "com.google.common.collect.ImmutableMap",
      "com.google.common.collect.AbstractIndexedListIterator",
      "com.google.common.collect.Maps$1",
      "org.joda.time.ReadableInstant",
      "ninja.session.Session",
      "org.joda.time.convert.NullConverter",
      "ninja.Results",
      "org.joda.time.tz.Provider",
      "org.joda.time.chrono.AssembledChronology$Fields",
      "org.joda.time.DurationFieldType",
      "org.joda.time.tz.NameProvider",
      "com.google.common.collect.ImmutableList$Builder",
      "org.joda.time.convert.ReadableInstantConverter",
      "org.joda.time.convert.StringConverter",
      "ninja.utils.NoHttpBody",
      "org.joda.time.convert.InstantConverter",
      "org.joda.time.chrono.AssembledChronology",
      "ninja.utils.SwissKnife$Converter",
      "org.joda.time.chrono.GJEraDateTimeField",
      "org.joda.time.tz.ZoneInfoProvider",
      "org.joda.time.chrono.BaseChronology",
      "org.joda.time.chrono.JulianChronology",
      "org.apache.commons.configuration.BaseConfiguration",
      "models.Card",
      "com.google.common.base.Equivalence",
      "com.google.common.base.CaseFormat",
      "com.google.common.base.Ascii",
      "org.joda.time.Chronology",
      "models.Suit",
      "org.joda.time.field.AbstractReadableInstantFieldProperty",
      "com.google.common.collect.Maps",
      "com.google.common.base.CharMatcher$Or",
      "org.joda.time.UTCDateTimeZone",
      "org.joda.time.LocalDate",
      "com.google.common.base.CaseFormat$StringConverter",
      "org.joda.time.chrono.BasicDayOfMonthDateTimeField",
      "org.joda.time.format.InternalParser",
      "org.joda.time.ReadablePartial",
      "org.joda.time.field.BaseDurationField"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ApplicationController_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "models.Card",
      "models.Suit",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.collect.RegularImmutableList",
      "com.google.common.collect.ObjectArrays",
      "com.google.common.collect.ImmutableList",
      "ninja.Result",
      "com.google.common.base.Optional",
      "com.google.common.base.Absent",
      "com.google.common.collect.Collections2",
      "com.google.common.collect.Maps",
      "org.joda.time.format.DateTimeFormat",
      "org.joda.time.DateTimeFieldType$StandardDateTimeFieldType",
      "org.joda.time.DurationFieldType$StandardDurationFieldType",
      "org.joda.time.DurationFieldType",
      "org.joda.time.DateTimeFieldType",
      "org.joda.time.format.DateTimeFormatterBuilder$TextField",
      "org.joda.time.UTCDateTimeZone",
      "org.joda.time.DateTimeZone",
      "ninja.utils.DateUtil",
      "org.joda.time.base.BaseDateTime",
      "org.joda.time.DateTime",
      "org.joda.time.convert.ConverterManager",
      "org.joda.time.convert.ReadableInstantConverter",
      "org.joda.time.convert.StringConverter",
      "org.joda.time.convert.CalendarConverter",
      "org.joda.time.convert.DateConverter",
      "org.joda.time.convert.LongConverter",
      "org.joda.time.convert.NullConverter",
      "org.joda.time.convert.ReadablePartialConverter",
      "org.joda.time.convert.ReadableDurationConverter",
      "org.joda.time.convert.ReadableIntervalConverter",
      "org.joda.time.convert.ReadablePeriodConverter",
      "org.joda.time.DateTimeUtils",
      "org.joda.time.chrono.BaseChronology",
      "org.joda.time.chrono.AssembledChronology",
      "org.joda.time.field.MillisDurationField",
      "org.joda.time.field.BaseDurationField",
      "org.joda.time.field.PreciseDurationField",
      "org.joda.time.field.PreciseDurationDateTimeField",
      "org.joda.time.field.PreciseDateTimeField",
      "org.joda.time.field.DecoratedDateTimeField",
      "org.joda.time.field.ZeroIsMaxDateTimeField",
      "org.joda.time.chrono.BasicChronology$HalfdayField",
      "org.joda.time.chrono.BasicChronology",
      "org.joda.time.chrono.BasicGJChronology",
      "org.joda.time.field.ImpreciseDateTimeField",
      "org.joda.time.chrono.BasicYearDateTimeField",
      "org.joda.time.field.ImpreciseDateTimeField$LinkedDurationField",
      "org.joda.time.chrono.GJYearOfEraDateTimeField",
      "org.joda.time.field.OffsetDateTimeField",
      "org.joda.time.field.DividedDateTimeField",
      "org.joda.time.field.DecoratedDurationField",
      "org.joda.time.field.ScaledDurationField",
      "org.joda.time.field.RemainderDateTimeField",
      "org.joda.time.chrono.GJEraDateTimeField",
      "org.joda.time.chrono.GJDayOfWeekDateTimeField",
      "org.joda.time.chrono.BasicDayOfMonthDateTimeField",
      "org.joda.time.chrono.BasicDayOfYearDateTimeField",
      "org.joda.time.chrono.BasicMonthOfYearDateTimeField",
      "org.joda.time.chrono.GJMonthOfYearDateTimeField",
      "org.joda.time.chrono.BasicWeekyearDateTimeField",
      "org.joda.time.chrono.BasicWeekOfWeekyearDateTimeField",
      "org.joda.time.field.UnsupportedDurationField",
      "org.joda.time.chrono.GregorianChronology",
      "org.joda.time.chrono.ISOYearOfEraDateTimeField",
      "org.joda.time.chrono.ISOChronology",
      "org.joda.time.tz.DateTimeZoneBuilder$PrecalculatedZone",
      "org.joda.time.tz.DateTimeZoneBuilder$DSTZone",
      "org.joda.time.tz.CachedDateTimeZone",
      "org.joda.time.chrono.ZonedChronology",
      "org.joda.time.chrono.ZonedChronology$ZonedDurationField",
      "org.joda.time.chrono.ZonedChronology$ZonedDateTimeField",
      "org.joda.time.chrono.GJLocaleSymbols",
      "org.joda.time.format.FormatUtils",
      "com.google.common.base.Present",
      "com.google.common.collect.SingletonImmutableList",
      "ninja.utils.SwissKnife",
      "com.google.common.base.CaseFormat$1",
      "com.google.common.base.CharMatcher",
      "com.google.common.base.CaseFormat$2",
      "com.google.common.base.CaseFormat$3",
      "com.google.common.base.CaseFormat$4",
      "com.google.common.base.CaseFormat$5",
      "com.google.common.base.CaseFormat",
      "com.google.common.base.Ascii"
    );
  }
}
