/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 02 21:33:59 GMT 2017
 */

package models;

import org.junit.Test;
import static org.junit.Assert.*;
import models.SpanishDeck;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SpanishDeck_ESTest extends SpanishDeck_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SpanishDeck spanishDeck0 = new SpanishDeck();
  }
}
