/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Dec 02 21:34:19 GMT 2017
 */

package conf;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Module_ESTest_scaffolding {

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "conf.Module"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init(); 
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.specification.version", "1.8"); 
            java.lang.System.setProperty("java.home", "C:\\Program Files\\Java\\jdk1.8.0_144\\jre"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\devon"); 
            java.lang.System.setProperty("java.awt.headless", "true"); 
                                java.lang.System.setProperty("user.dir", "C:\\Users\\devon\\Documents\\Java Projects\\AcesUp"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\devon\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("line.separator", "\r\n"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Module_ESTest_scaffolding.class.getClassLoader() ,
      "com.google.inject.Module",
      "com.google.inject.Key",
      "com.google.inject.binder.AnnotatedConstantBindingBuilder",
      "com.google.inject.spi.TypeConverter",
      "com.google.inject.binder.AnnotatedBindingBuilder",
      "org.aopalliance.intercept.Interceptor",
      "com.google.inject.Binder",
      "com.google.inject.spi.Message",
      "org.aopalliance.aop.Advice",
      "com.google.inject.spi.ProvisionListener",
      "conf.Module",
      "com.google.inject.Scope",
      "com.google.inject.binder.ScopedBindingBuilder",
      "com.google.inject.Stage",
      "org.aopalliance.intercept.MethodInterceptor",
      "com.google.inject.Provider",
      "com.google.inject.binder.LinkedBindingBuilder",
      "com.google.inject.spi.Element",
      "com.google.inject.ScopeAnnotation",
      "com.google.inject.matcher.Matcher",
      "com.google.inject.spi.TypeListener",
      "com.google.inject.MembersInjector",
      "com.google.inject.TypeLiteral",
      "com.google.inject.AbstractModule",
      "com.google.inject.Singleton"
    );
  } 

  private static void resetClasses() {
  }
}
